services:
  mongo:
    image: mongo:7
    container_name: grocery-mongo
    ports: ["27017:27017"]
    volumes:
      - grocery_data:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "mongodb://localhost:27017/admin",
          "--eval",
          "db.runCommand({ ping: 1 }).ok",
        ]
      interval: 5s
      timeout: 3s
      retries: 40
  seeder:
    build: .
    command: ["node", "dist/scripts/seed.js"]
    env_file: .env
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      MONGO_URI: ${MONGO_URI}
    restart: "no"
  api:
    build: .
    container_name: grocery-api
    depends_on: [mongo]
    env_file: .env
    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}

    ports: ["3000:3000"]
    command: ["node", "dist/src/server.js"]
volumes:
  grocery_data:
